# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee6b47a87c6288cdec4c6c338db4d854fee931f4f395268e08a5a21c8bc2dd5b3775304b12542a1450c1ff3d447b5929f0bb8e026f9a428d39320e4d8e4564b

test:
  secret_key_base: daef762e885fa1922cbad15d15827827627dbf6bee816577c8918609f85e0db6e65313e82b05abe069d4abf22fb6c343e28c63ba10f2f33d38f20eb378a5e06d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
